spring:
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://localhost:3306/enpdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    org:
      hibernate:
        SQL:
          TRACE
        type:
          descriptor:
            sql:
              BasicBinder:
                TRACE
jwt:
  header: Authorization
  secret: "4t7w!z%C&F)J@NcRfUjXn2r5u8x/A?D(G-KaPdSgVkYp3s6v9y$B&E)H@MbQeThW"
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

